### ISSUE TITLE
MobileClient missing debug module

### ISSUE THREAD

**Issue by shukla-amit** [Microsoft/Bing-Maps-Fleet-Tracker#7]
Error
Close
Runtime Error
Cannot find module "../debug/debug"
Stack
Error: Cannot find module "../debug/debug"
   at Anonymous function (http://localhost:8100/build/main.js:45697:1)
   at __webpack_require__ (http://localhost:8100/build/main.js:20:12)
   at Anonymous function (http://localhost:8100/build/main.js:86901:22)
   at __webpack_require__ (http://localhost:8100/build/main.js:20:12)
   at Anonymous function (http://localhost:8100/build/main.js:86775:22)
   at __webpack_require__ (http://localhost:8100/build/main.js:20:12)
   at Anonymous function (http://localhost:8100/build/main.js:86969:22)
   at __webpack_require__ (http://localhost:8100/build/main.js:20:12)
   at Anonymous function (http://localhost:8100/build/main.js:66:11)
   at Global code (http://localhost:8100/build/main.js:1:11)
Ionic Framework: 2.0.0-rc.5
Ionic Native: 2.2.11
Ionic App Scripts: 1.3.12
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 9.5.0
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

**Comment by momohs** [comment]
It looks like a couple of files were omitted from the repository due to a mistake in the .gitignore. Will fix that.

**Comment by momohs** [comment]
@shukla-amit the fix is on the master branch now. Please try it out and let me know if you still have any problems

**Comment by momohs** [comment]
I'll close this issue for now. Please feel free to re-open if you still have any problems.

**Comment by ronpack** [comment]
I am available to help out with code or anything needed with this project. Let me know if I can help!

Thank you,
Ron Pack

________________________________

**Comment by momohs** [comment]
@ronpack help is always appreciated. A good place to start contributing is to address the issues marked with "good first issue" to get yourself familiar with the code base. Thanks.
